###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

#    memcached:
#      image: memcached:alpine
#      container_name: test-memcached

    redis:
      image: redis:alpine
      container_name: authback-redis

    mysql:
      image: mysql:8.0
      container_name: authback-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=test123
        - MYSQL_USER=test123
        - MYSQL_PASSWORD=123
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: authback-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: authback-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

